spring:
  application:
    name: Alura-user-management
    version: 1.0.0.alpha
  datasource:
    url: jdbc:mysql://localhost:3306/alura_user_management
    username: sprig
    password: sprigpassword
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration